### ISSUE TITLE
Ajustes en API notificacion_api.

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_api#17]
Realizar ajustes necesarios en API notificacion_api para permitir realizar notificaciones al interior de los sistemas y mediante correo electrónico.

**Criterios de aceptación**

- [x] Commit con los cambios realizados.

**Comment by FelipeVel** [comment]
Cuando se analizó la configuración del api existente vimos que era una configuración muy antigua y que era mejor crear un nuevo repositorio, se creó el repositorio de notificacion_mid y allí se configuró todo para poder montar el api desarrollado, hasta éste momento con el [commit más actualizado](https://github.com/udistrital/notificacion_mid/commit/a4d6b0d6a2aa84e80abbdfd16f798d5e7a8c4875) se tienen las siguientes funciones:

* Suscripcion a mensajería desde cualquier protocolo
* Creacion de topics para el manejo de distribución de mensajes
* Listado de topics para el fácil acceso hacia los arn para cuando un desarrollador los necesite
* Publicacion de notificaciones hacia el servicio AWS
* Creación de colas para recibir mensajes
* Consulta de mensajes en cola
