### ISSUE TITLE
Configuración de servicios en AWS.

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_api#18]
Realizar la configuración de servicios en AWS necesarios para el funcionamiento del API notificaciones_api.

**Criterios de aceptación**

- [x] Evidencia de configuración realizada en AWS y carga de configuración en AWS institucional.

**Comment by FelipeVel** [comment]
Se prueba configuración para el funcionamiento del API en local con credenciales personales para luego adaptar esta configuración en servicios AWS institucionales.

Dentro de la configuración en los servicios finalmente sólo se tuvo en cuenta la creación de un nuevo rol para manejo de operaciones que serán realizadas por el mid desarrollado.
