### ISSUE TITLE
Generar Documentación y Plan de Trabajo

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#2]
Se necesita subir documentación relacionada con los diseños de arquitectura (y los que sean considerados como necesarios) al repositorio. Se proponen:

- Diseño de componentes
- Diseño de infraestructura

Se pueden usar las capas necesarias o las mezclas necesarias, siempre y cuando aporten una lectura mejorada a la solución.

**Nota**: Se busca legibilidad, claridad en lo que se expresa y que abarque la solución completa.

Además anexar el link de un documento para plan de trabajo de las siguientes etapas; El plan de trabajo debe ser claro y abarcar la la solución completa por lo que parte del análisis realizado en la primera fase y busca tener un insumo para el control y planeación de las siguientes etapas, por lo que debe ser lo más apegado a la realidad posible.

**Comment by fabianLeon** [comment]
[Enlace del plan de trabajo del sistema de notificaciones](https://docs.google.com/spreadsheets/d/1KqAGZ00voKr77HsmGzPToczcdo4Rw4Rlws6nP3zaoRI/edit?usp=sharing)

**Comment by fabianLeon** [comment]
[Enlace de documento de análisis](https://docs.google.com/document/d/17eiVZUgqhldM_BC394jqwqDpqxeFVGgRjuXo5UXNpv4/edit?usp=sharing)

**Comment by fabianLeon** [comment]
Se crea repositorio [notificacion_documentacion](https://github.com/udistrital/notificacion_documentacion).

**Comment by FredyRodriguezR** [comment]
[Diagramas en archimate de estado actual y propuesta de componentes](https://github.com/udistrital/notificacion_documentacion/commit/777c77eb342d5e53c5afa97540751ce955b10c05)

[Capa de persistencia incluida en la vista (Propuesta) de ComponentesNotificacion.archimate y correciones en el README](https://github.com/udistrital/notificacion_documentacion/commit/17338acc8718dd02094828356722d4603a878066)

[Capa de persistencia incluida en la vista (Actual) de ComponentesNotificacion.archimate](https://github.com/udistrital/notificacion_documentacion/commit/6bd1933a3c9ab30481f6f6136169842c64364cfe)

**Comment by faparraf** [comment]
Documentos validados
