### ISSUE TITLE
Pruebas de carga y seguridad - Notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_api#20]
Solicitar con anticipación las pruebas de carga y seguridad correspondientes al desarrollo realizado en el API notificacion_api.

**Criterio de aceptación**

- [x] Documento con los resultados de las pruebas aplicadas.

**Nota:**

El documento resultado de las pruebas es entregado por parte del equipo de seguridad.
Se debe registrar en este ISSUE la realización de los ajustes solicitados en el documento resultado.

**Comment by a52290451** [comment]
Se solicitan pruebas de carga y seguridad el día 11 de noviembre:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=44332

**Comment by FelipeVel** [comment]
Se adjunta la [lista de cambios](https://drive.google.com/file/d/1SyxPMR3_Zq73wZIIAraAbv2o4OvHOWo5/view?usp=sharing) hechos al api de notificaciones para corrección de errores encontrados en pruebas de carga.
