### ISSUE TITLE
Pruebas funcionales y de usabilidad - Notificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_api#22]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con el desarrollo del API notificacion_api.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

Nota: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit?usp=sharing) dispuesto para la aplicación de este tipo de pruebas.

**Comment by FelipeVel** [comment]
Se adjunta el [checklist](https://docs.google.com/document/d/1IuN2zEyuU7O9LsOjOhe2Wt_NldXLO3Ly/edit?usp=sharing&ouid=107699434263475311303&rtpof=true&sd=true) seguido para despliegue en ambiente de pruebas

**Comment by FelipeVel** [comment]
Se adjunta el [documento de registro de pruebas funcionales](https://docs.google.com/spreadsheets/d/1SuAhfDHYM0OxwZ1mrV-MM36aEN5v8Cia/edit?usp=sharing&ouid=107699434263475311303&rtpof=true&sd=true)

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.
