### ISSUE TITLE
Generar DDL para modificación en base de datos

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#4]
La organización busca tener un modelo de base de datos para el componente de notificaciones con el que se logre abarcar la funcionalidad completa del módulo por lo que se necesita un script DDL que modifique las estructuras actuales y añada nuevas con el fin de que se satisfagan las necesidades de datos que requiere el API.

**Criterios de aceptación:**
- **Transición** entre API's actuales y los futuros
> No se puede permitir romper un API actual

**Entregables**
- [x] Script publicado en ambiente _flyway_ para versión de base de datos.
- [ ] Aprobaciones en _flyway_ hasta ambiente de producción

**Comment by fabianLeon** [comment]
- Se crea tabla configuracion.notificacion_estado_usuario
- Se realiza la estandarización de la tabla configuracion.notificacion_estado
- Se crean los campos alias, estilo_icono en la tabla configuracion.aplicacion

[commit](https://gogs.udistritaloas.edu.co/core/udistrital_core_db/commit/f459e4de8f50270dc46191be116af43e85faf960)

Se deja como comentario código para: 

- Eliminación de constraint FK_notificacion_estado_notificacion_estado en tabla notificacion
- Eliminación de columna usuario en tabla notificacion
- Eliminación de columna estado_notificacion en tabla notificacion

**Comment by FredyRodriguezR** [comment]
Se genera el modelo de la BD Configuracion en pgmodeler [commit](https://github.com/udistrital/notificacion_documentacion/commit/029e2b8ce9826a0e7b9d1e470abe3a1ecb8b9eba)
