### ISSUE TITLE
Ajustes en API de notificaciones

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#6]
La organización requiere que el API de notificaciones sea ajustado de acuerdo a las modificaciones en el modelo de datos realizado con anterioridad con el fin de conseguir una **completa trazabilidad** del servicio funcional.

**Entregables:**
- [x] Adaptación de librería para notificaciones de go https://github.com/udistrital/notificaciones_lib para que se ajuste al modelo de datos propuesto.
- [x] Adaptación de pool's de usuarios en https://github.com/udistrital/notificacion_api establecidos en la conexión webSocket con base a las modificaciones propuestas en base de datos y dependiendo de los escenarios propuestos.

**Criterios de aceptación:**
- Cambios en repositorio del API.
- API desplegado en ambiente Cloud.

> Referenciar dichos cambios mediante el uso de `udistrital/notificacion_api#6`

**Comment by FredyRodriguezR** [comment]
[Nuevo flujo para consultar notificaciones en notificacion_api](https://github.com/udistrital/notificacion_api/commit/e594df64ccb2d06b96d848aa92d657a5846368b9)

**Comment by fabianLeon** [comment]
Se finaliza proceso de transición de base de datos, ajustando con el [commit](https://gogs.udistritaloas.edu.co/core/udistrital_core_db/commit/22a329938234f39fb80443422c7394a2e57cb2ca), se realiza despliegue en ambiente de pruebas aprobado por el DBA @fnrojash

**Comment by fabianLeon** [comment]
se crea rama [test](https://github.com/udistrital/notificacion_api/tree/test) se ajusta [.drone.yml](https://github.com/udistrital/notificacion_api/blob/test/.drone.yml) para despliegue.

[Error de Integración contínua](https://ci.portaloas.udistrital.edu.co/udistrital/notificacion_api/13/5)
```
github.com/udistrital/go-awsecs/cmd/update-aws-ecs-service
+ AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} AWS_REGION=$AWS_REGION $GOPATH/bin/update-aws-ecs-service -cluster $CLUSTER -service $SERVICE -container-image $container_name=$MYCONTAINER
2019/06/27 16:45:50 the service does not exist
```

Al parecer aún no ha sido creado el entorno.
