### ISSUE TITLE
Componentes gráficos para Angular 1.x +

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#7]
La organización busca que el uso del componente de notificaciones sea estandarizado y común entre los diferentes clientes estáticos desarrollados, por lo que se requiere que se generen componentes para dichos clientes sobre los que se pueda consumir los servicios de notificaciones y generar la doble vía de comunicación necesaria.

**Entregables:**
- [x] Componente Angular 1.X desplegado en clientes propios (Grupo Core).
- [x] Componente Angular 6.X desplegado en cliente de conveniencia (Grupo Core).

**Criterios de aceptación:**
- Cambios en repositorio de clientes.
- Cambios desplegados en ambiente Cloud.

> Referenciar dichos cambios mediante el uso de `udistrital/notificacion_api#7`

**Comment by fabianLeon** [comment]
Junto a @FredyRodriguezR  se realiza la construcción del componente para angular7 y se publica en npm con el nombre de [notioas](https://www.npmjs.com/package/notioas#ejemplos),

**Comment by fabianLeon** [comment]
Se realiza construcción de directiva de notificaciones, reajustando interfaz para que sea lo más parecida al componente armado en angular7,se implementa en [cumplidos_cliente](https://github.com/udistrital/cumplidos_cliente) con [pullRequest](https://github.com/udistrital/cumplidos_cliente/pull/4)- [comparación de ramas](https://github.com/udistrital/cumplidos_cliente/compare/gaia_dev...notificacionv2?expand=1)
