### ISSUE TITLE
Modificación del cliente de configuración

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#8]
La organización requiere que el cliente de configuración (gráfico) sea modificado para ajustarse al nuevo modelo de datos y de API desarrollado anteriormente con el fin de lograr **configurar las notificaciones** necesarias desde el mismo cliente.

**Entregables:**
- [x] Cambios evidenciados en el repositorio necesario.
- [x] Cambios desplegados en ambiente Cloud

> Referenciar dichos cambios mediante el uso de `udistrital/notificacion_api#8`

**Comment by fabianLeon** [comment]
se crea repo para cliente de configuracion con construcción de crud base para ajustar -> [commit](https://github.com/udistrital/configuracion_cliente_v2)

**Comment by FredyRodriguezR** [comment]
Mejoras realizadas al modulo de notificaciones:
- Integracion de [servicio](https://github.com/udistrital/configuracion_api/commit/49fda348e632af52051fb15c7f3137d2cc214412) para cambiar las notificaciones de noleidas a leidas [commit](https://github.com/udistrital/configuracion_v2_cliente/commit/e06622f6f160d2778ab9b6896e25074e314313a0)
- Mejoras visuales de notificaciones y formateo de fechas con moment [commit](https://github.com/udistrital/configuracion_v2_cliente/commit/d193c6fad08cee981a59f2b870b2dd67feb903d6)
- Acceso a mensaje y link desde Content.Message [commitCliente](https://github.com/udistrital/configuracion_v2_cliente/commit/9ce41fcb52f1a1cbccb4069e2370bb79e95525d5) [commitLib](https://github.com/udistrital/notificaciones_lib/commit/737bdaddc04c5c209053c49afea967cc8504e0a4)
- Integracion de iconos de notificacion de forma dinamica [commit](https://github.com/udistrital/configuracion_v2_cliente/commit/b65f58adde47fcd02752bce452b8082bef2d3852)

**Comment by fabianLeon** [comment]
Por conversación con @corio27 el cliente de configuración va a estar en el entorno del 254
