### ISSUE TITLE
Despliegue de módulo de notificaciones

### ISSUE THREAD

**Issue by faparraf** [udistrital/notificacion_api#9]
La organización requiere que los ajustes hechos al módulo de notificaciones sea desplegado en su **totalidad** en ambiente Cloud comprobando la completa trazabilidad del servicio y su completa funcionalidad.

**Despliegues solicitados:**
- [x] Aplicación prueba AngularJs (configuracion).
- [x] Aplicación prueba angular2x.
- [x] configuracion_api. 
- [x] notificacion_api.
- [x] notificaciones_lib.

**Criterios de Aceptación:**
- Publicación en WSO2 preproducción para redirección de solicitudes e implementación de autenticación única.
- Retroalimentación de publicación WSO2 preproducción, pruebas de consumo y definición de ajustes tanto a los servicios como a la configuración WSO2 preproducción.

> Referenciar dichos cambios mediante el uso de `udistrital/notificacion_api#9`

**Comment by FredyRodriguezR** [comment]
Ajuste en el Readme de la libreria notioas [commit](https://github.com/udistrital/configuracion_v2_cliente/commit/5340a76d1f1aa5cc852419e14638256f27febd0a)

**Comment by FredyRodriguezR** [comment]
Creacion de [servicio](https://github.com/udistrital/configuracion_api/commit/725b1a1eccf63f7617da1ec33946dfc410437593) que obtiene la configuracion para su posterior tratamiento con regex y actualizacion para su funcionamiento de forma dinamica, incluyendo un proceso de dockerizacion [commit](https://github.com/udistrital/configuracion_api/commit/de00227213e3b79dcecd45b2f6d7487d9a853026)

**Comment by fabianLeon** [comment]
Se realizó la configuración de wso2 para los apis que están en el entorno test, se evidenció que el flujo de autenticación funciona, pero el payload  no retorna el parametro role.
solo devuelve 
```
{
  "at_hash": "ZNHFZZ_h06fOXh9oSNlquA",
  "sub": "fdsanchezl",
  "aud": [
    "dmh4U7ixf4WnaXYPPVemP5DJZtca"
  ],
  "azp": "dmh4U7ixf4WnaXYPPVemP5DJZtca",
  "auth_time": 1565751487,
  "iss": "autenticacion.portaloas.udistrital.edu.co",
  "exp": 1565755090,
  "nonce": "ff34a92621cec73a6ea0abbe3f7435b1",
  "iat": 1565751490
}
```
pendiente respuesta de @corio27

**Comment by fabianLeon** [comment]
EL proceso del flujo de notificaciones ha sido interrumpido por un error de base de datos:
`
pq: permission denied for sequence notificacion_estado_usuario_id_seq
`
Se procede a solicitar amablemente al DBA @fnrojash , se verifica funcionamiento ok.

El websocket se cae cuando no hay envío de mensajes, se procede a inspeccionar solución del lado del cliente

**Comment by fabianLeon** [comment]
se ajusta funcionalidad de conexión para que el envio de ping posterior a la conexión del lado del cliente, evitando así caidas del websocket, se realiza pruebas en ambiente test y pruebas del 254

pendiente cableado de websocket por wso2, esto debido a que las pruebas realizadas de inclusión de subprotocolos mediante el uso de webocket de rxjs no han sido exitosas.

**Comment by fabianLeon** [comment]
Se realiza acompañamiento y ajuste para despliegue del cliente de configuración en entorno test.
[https://pruebasconfiguracion.portaloas.udistrital.edu.co](https://pruebasconfiguracion.portaloas.udistrital.edu.co.) 
Se construye flujo de autenticación para este cliente en wso2.

Se apoya a @FredyRodriguezR  en la construcción del body necesario para enviar notificación sin librería.

**Comment by fabianLeon** [comment]
Se detecta que las secuencias 
**menu_opcion_id_seq**
**menu_opcion_padre_id_seq**
**perfil_x_menu_opcion_id_seq**
de la base de datos del ambiente **test**  están atrasadas con respecto a los registros de las respectivas tablas,  lo que ocasiona que no se pueda realizar la gestión de menús desde la aplicación [configuracion_test](https://pruebasconfiguracion.portaloas.udistrital.edu.co/).

Se debe solicitar amablemente al dba que ajuste dichas secuencias.

**Comment by faparraf** [comment]
Los recursos de publicación del servicio de forma pública han sido desplegados en los stacks de la organización

**Comment by fabianLeon** [comment]
se realizan pruebas correspondientes al **proceso de notificaciones**.

- se detecta error con variable de entorno, pendiente prueba de notificaciones con librería notioas_lib en configuracion_api,.

- se detecta problemas de conexion con el websocket despues de aproximadamente 24 horas de trabajo, deja de admitir conexiones, posiblemente a causa de algun tipo de conexiones abiertas.

- se detecta un problema en la libreria del lado del cliente al realizar el cambio de estado de enviado a visto, el componente pierde la notificacion que le fue enviada.
